# neo4j 
# Flask server

version: '3.7'
services:
  neo4j:
    image: neo4j:5.25.1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_AUTH:-example123456789}
    volumes:
      - ./data:/data

    

  flask:
    build: ./website
    ports:
      - "80:80"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_AUTH:-example123456789}
